### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by astroash** [FACG4/week3-api-food-recipe-app#9]
It's a common convention to name javascript functions and variables using camelCase & file names with snake_case 😊

https://github.com/FACG4/week3-api-food-recipe-app/blob/f7d31c88c95b06cbc0280c2b6e8db528829f0bae/public/logic.js#L42

**Comment by RamyAlshurafa** [comment]
@astroash 
thank you so much for your review .
we solved it

**Comment by astroash** [comment]
Sweet!
